# Generated by Django 5.0.3 on 2024-04-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_recipe', '0002_alter_recipe_image_alter_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_images/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps_images/'),
        ),
    ]
