# Generated by Django 5.0.3 on 2024-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_recipe', '0003_alter_recipe_image_alter_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
