# Generated by Django 5.0.3 on 2024-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_recipe', '0004_recipe_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='for_clash',
            field=models.BooleanField(default=False),
        ),
    ]
