# Generated by Django 5.0.3 on 2024-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_ai', '0002_alter_airecipe_image_alter_aistep_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistep',
            name='image',
        ),
        migrations.AlterField(
            model_name='airecipe',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
