# Generated by Django 5.0.3 on 2024-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_ai', '0004_alter_airecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecipe',
            name='image',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
