# Generated by Django 5.0.3 on 2024-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_ai', '0006_airecipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
