# Generated by Django 5.0.3 on 2024-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
