# Generated by Django 5.0.3 on 2024-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='awardBurger',
            field=models.BooleanField(default=False),
        ),
    ]
