# Generated by Django 5.0.3 on 2024-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_customuser_awardburger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='awardBake',
            field=models.BooleanField(default=False),
        ),
    ]
