# Generated by Django 5.0.3 on 2024-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_customuser_awardbake'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='top_ten_achievement',
            field=models.BooleanField(default=False),
        ),
    ]
